### ISSUE TITLE
issue on mcl stage

### ISSUE THREAD

**Issue by asher-616** [arzwa/wgd#21]
Hi, I'm trying to run the mcl stage on a genome I got and the wgd_blast is empty after the stage.
I'm not sure why.
this is what I get on the screen:
```
2019-08-15 16:53:27: INFO
2019-08-15 16:53:27: INFO
2019-08-15 16:53:27: INFO       mcl 14-137
Copyright (c) 1999-2014, Stijn van Dongen. mcl comes with NO WARRANTY
to the extent permitted by law. You may redistribute copies of mcl under
the terms of the GNU General Public License.
2019-08-15 16:53:27: INFO       CDS sequences provided, will first translate.
Sequence length != multiple of 3 for chr1!
In-frame STOP codon in chr1 at position 0:3
In-frame STOP codon in chr2 at position 27:30
Sequence length != multiple of 3 for chr3!
In-frame STOP codon in chr3 at position 45:48
In-frame STOP codon in chr4 at position 51:54
Sequence length != multiple of 3 for chr5!
In-frame STOP codon in chr5 at position 3:6
In-frame STOP codon in chr6 at position 57:60
Sequence length != multiple of 3 for chr7!
In-frame STOP codon in chr7 at position 171:174
Sequence length != multiple of 3 for chr8!
In-frame STOP codon in chr8 at position 45:48
In-frame STOP codon in chr9 at position 231:234
Sequence length != multiple of 3 for chr10!
In-frame STOP codon in chr10 at position 60:63
Sequence length != multiple of 3 for chr11!
In-frame STOP codon in chr11 at position 42:45
Sequence length != multiple of 3 for chr12!
In-frame STOP codon in chr12 at position 45:48
Sequence length != multiple of 3 for chr13!
In-frame STOP codon in chr13 at position 117:120
In-frame STOP codon in chrUn at position 9:12
100% (15 of 15) |########################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
2019-08-15 16:53:37: WARNING    There were 23 warnings during translation
2019-08-15 16:53:37: INFO       Writing blastdb sequences to db.fasta.
2019-08-15 16:53:37: INFO       Writing query sequences to query.fasta.
2019-08-15 16:53:37: INFO       Performing all-vs.-all Blastp (this might take a while)
2019-08-15 16:53:37: INFO       Making Blastdb
makeblastdb: symbol lookup error: /powerapps/share/mpi/openmpi-1.10.4.c7/lib/libmpi_cxx.so.1: undefined symbol: ompi_mpi_char
2019-08-15 16:53:37: INFO       Running Blastp
2019-08-15 16:53:37: INFO       blastp -db wgd_blast/37a19200e9d1ae.db.fasta -query wgd_blast/37a19200ea5b22.query.fasta -evalue 1e-10 -outfmt 6 -num_threads 4 -out wgd_blast/botznik-chr.fa.blast.tsv
2019-08-15 16:53:37: INFO       All versus all Blastp done
rm: cannot remove ‘wgd_blast/37a19200e9d1ae.db.fasta.phr’: No such file or directory
rm: cannot remove ‘wgd_blast/37a19200e9d1ae.db.fasta.pin’: No such file or directory
rm: cannot remove ‘wgd_blast/37a19200e9d1ae.db.fasta.psq’: No such file or directory
2019-08-15 16:53:37: INFO       Blast done
2019-08-15 16:53:37: INFO       Performing MCL clustering (inflation factor = 2.0)
Traceback (most recent call last):
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/bin/wgd", line 11, in <module>
    sys.exit(cli())
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/wgd_cli.py", line 293, in mcl
    inflation_factor, eval_cutoff, output_dir, n_threads)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/wgd_cli.py", line 442, in blast_mcl
    ava_graph = ava_blast_to_abc(blast_results)
  File "/powerapps/share/centos7/miniconda/miniconda3-4.5.11/lib/python3.7/site-packages/wgd/blast_mcl.py", line 137, in ava_blast_to_abc
    with open(ava_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'wgd_blast/botznik-chr.fa.blast.tsv'
```

**Comment by arzwa** [comment]
It seems you are using chromosome sequences? Tools in `wgd` only make sense for well-defined coding DNA sequences (CDS). You will need to provide gene models.
