### ISSUE TITLE
wgd dmd error

### ISSUE THREAD

**Issue by yuzhenpeng** [arzwa/wgd#30]
Dear teams,
When I used the `wgd dmd`, it comes the following error:

Traceback (most recent call last):
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/bin/wgd", line 8, in <m                                                               odule>
    sys.exit(cli())
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/wgd_cli.py", line 528, in dmd
    s[0].get_paranome(inflation=inflation, eval=eval)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/wgd/diamond.py", line 94, in get_paranome
    df = self.run_diamond(self, eval=eval)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/wgd/diamond.py", line 71, in run_diamond
    self.make_diamond_db()
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/site-pack                                                               ages/wgd/diamond.py", line 65, in make_diamond_db
    out = sp.run(cmd, capture_output=True)
  File "/Bio/home/Yanglab/Yuzhenpeng/miniconda2/envs/wgd/lib/python3.6/subproces                                                               s.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'

My computer used the python3 environment. It can run 'wgd mcl' very well. Could you please give me a help.
Thank you.

Zhenpeng

**Comment by arzwa** [comment]
Hi, `wgd dmd` requires Python3.7 or higher, this error is due to some changes in Python base libraries, so please try again using a newer Python version.
