### ISSUE TITLE
Is the singularity installation up to date?

### ISSUE THREAD

**Issue by smallfishcui** [arzwa/wgd#56]
Hi,

I installed the singularity container on a server, and the function --version, and dmd doesn't work.
ALso when I try to run mcl analysis, it constantly complains cds file can't be find, or the input folder is read-only, system error.
Traceback (most recent call last):
  File "/usr/local/bin/wgd", line 11, in <module>
    load_entry_point('wgd==1.0', 'console_scripts', 'wgd')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/wgd_cli.py", line 293, in mcl
    inflation_factor, eval_cutoff, output_dir, n_threads)
  File "/usr/local/lib/python3.6/dist-packages/wgd_cli.py", line 347, in blast_mcl
    os.mkdir(output_dir)
FileNotFoundError: [Errno 2] No such file or directory: './cds.out'

Can you help with that?

Thanks,
Cui

**Comment by arzwa** [comment]
Sorry, I haven't used Singularity containers in two years, so I have a look whether I can update this. For sure `dmd` won't work, because the container doesn't include a diamond installation currently. For the error you note above, are you using the commands in the form `singularity exec wgd.simg wgd <command>`?

**Comment by smallfishcui** [comment]
Hi,
Thank you for the information. Does it run if I have diamond in the PaTH?
Yes I run it like that. The help menu runs fine, and then it brokes when
running real data.

Cui

**Comment by Cecilia-Sensalari** [comment]
Hi, 
There has been an update with Singularity, now it supports diamond and it can print the version (see README).

Cheers,
Cecilia
