### ISSUE TITLE
bokeh visualisation error

### ISSUE THREAD

**Issue by ardy20** [arzwa/wgd#81]
Hello

I installed WGD for whole genome duplication analysis. I run the bokeh and the viz command as following but I get error when I run on your example data . Could you please guide how to solve this?

bokeh serve &

wgd viz -i -ks ath.ks.tsv

Traceback (most recent call last):
  File "/home/usr/miniconda3/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/home/usr/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/usr/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/usr/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/usr/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/usr/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/usr/miniconda3/lib/python3.9/site-packages/wgd_cli.py", line 1289, in viz
    viz_(
  File "/home/usr/miniconda3/lib/python3.9/site-packages/wgd_cli.py", line 1355, in viz_
    histogram_bokeh(dists_files, labels)
  File "/home/usr/miniconda3/lib/python3.9/site-packages/wgd/viz.py", line 389, in histogram_bokeh
    from bokeh.io import curdoc
  File "/home/usr/miniconda3/lib/python3.9/site-packages/bokeh/io/__init__.py", line 51, in <module>
    from .export import export_png
  File "/home/usr/miniconda3/lib/python3.9/site-packages/bokeh/io/export.py", line 34, in <module>
    from ..embed import file_html
  File "/home/usr/miniconda3/lib/python3.9/site-packages/bokeh/embed/__init__.py", line 54, in <module>
    from .server import server_document
  File "/home/usr/miniconda3/lib/python3.9/site-packages/bokeh/embed/server.py", line 29, in <module>
    from ..core.templates import AUTOLOAD_TAG, FILE
  File "/home/usr/miniconda3/lib/python3.9/site-packages/bokeh/core/templates.py", line 43, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (/home/usr/miniconda3/lib/python3.9/site-packages/jinja2/__init__.py)

**Comment by Wyinghao** [comment]
Hello, I also encountered the same problem, I would like to ask you if you solve it

**Comment by heche-psb** [comment]
Hi, in the next [version](https://github.com/heche-psb/wgd) we're working on, we don't maintain the bokeh related function in `wgd viz` any more, but more focused on the implementation of mixture modeling (ELMM for instance). The problem you encounter might be due to the higher version of bokeh in python3.9 you used. It might help if you try with lower version instead.
