### ISSUE TITLE
Singularity error with wgd syn

### ISSUE THREAD

**Issue by tylerdodgeball** [arzwa/wgd#83]
When using singularity container to run wgd syn, I receive the following error:

Traceback (most recent call last):
  File "/usr/local/bin/wgd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wgd_cli.py", line 851, in syn
    syn_(
  File "/usr/local/lib/python3.8/dist-packages/wgd_cli.py", line 881, in syn_
    from wgd.viz import plot_selection, syntenic_dotplot
  File "/usr/local/lib/python3.8/dist-packages/wgd/viz.py", line 28, in <module>
    from .modeling import filter_group_data
  File "/usr/local/lib/python3.8/dist-packages/wgd/modeling.py", line 26, in <module>
    from sklearn import mixture
ModuleNotFoundError: No module named 'sklearn'

**Comment by tylerdodgeball** [comment]
I should add that the command being used is the following:

singularity exec --bind $PWD --no-home wgd.sif wgd syn file1 file2

**Comment by tylerdodgeball** [comment]
This is using singularity-ce version 3.11.0-bionic.
